"use client";

import { useState } from "react";

const pillars = [["⌂", "Safe Housing", "A stable, loving environment where every girl can feel secure and valued."], ["♡", "Healing", "Trauma-informed care, mentorship, and emotional support for the whole person."], ["⌁", "Education & Empowerment", "Life skills, education, and opportunities for a brighter tomorrow."]];
const team = [["https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=700&q=80", "Founder", "Founder & Executive Director"], ["https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=80", "Programs Lead", "Director of Programs"], ["https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=700&q=80", "Community Lead", "Director of Operations"]];
function Mark() { return <span className="mark" aria-hidden="true"><i /><i /><i /><i /></span>; }
export default function HomePage() { const [open,setOpen]=useState(false); const close=()=>setOpen(false); return <>
  <header className="site-header"><div className="shell nav"><a className="brand" href="#home" onClick={close}><Mark/><span>Rosewill<br/>Loving Arms</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Open menu" aria-expanded={open}>{open?"×":"☰"}</button><nav className={open?"links open":"links"}><a href="#about" onClick={close}>About</a><a href="#programs" onClick={close}>Programs</a><a href="#impact" onClick={close}>Impact</a><a href="#leadership" onClick={close}>Get Involved</a><a href="#contact" onClick={close}>Contact</a><a className="button small" href="#donate" onClick={close}>Donate</a></nav></div></header>
  <main id="home"><section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Safe. Supported. Empowered.</p><h1>A safe place to heal.<br/><em>A future to grow into.</em></h1><p className="intro">We provide a compassionate, stable foundation for girls and young women to heal, learn, and build the confidence to shape their own futures.</p><div className="actions"><a className="button" href="#donate">Donate now <b>→</b></a><a className="button ghost" href="#programs">Our programs</a></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=85" alt="Young women walking together outside"/></div></div></section>
  <section className="mission"><div className="shell mission-grid"><p className="eyebrow">Our mission</p><h2>To provide a safe, supportive and nurturing environment for girls and young women to heal, learn and grow into confident, independent futures.</h2></div></section>
  <section id="programs" className="section shell"><div className="head"><div><p className="eyebrow">How we show up</p><h2>Care with a purpose.</h2></div><p>Our work begins with safety and grows through support, opportunity, and a real sense of possibility.</p></div><div className="pillars">{pillars.map(([icon,title,text])=><article className="pillar" key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p><a href="#how">Explore <b>→</b></a></article>)}</div></section>
  <section id="about" className="story"><div className="shell story-grid"><div className="story-photo"><img src="https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1100&q=85" alt="A woman smiling"/></div><div><p className="eyebrow">Our story</p><h2>A story of hope and purpose.</h2><p>Rosewill Loving Arms began with a belief that every girl deserves more than a safe place to land—she deserves a listening ear, a steady hand, and a future full of possibility.</p><a className="text-link" href="#values">Read our story →</a></div></div></section>
  <section id="impact" className="impact"><div className="shell"><p className="eyebrow">Our impact <small>Illustrative first-demo figures</small></p><div className="stats"><div><strong>150+</strong><span>Girls Supported</span></div><div><strong>92%</strong><span>Graduate or Move to Independent Living</span></div><div><strong>10+</strong><span>Community Partners</span></div></div></div></section>
  <section id="leadership" className="team"><div className="shell"><div className="head"><div><p className="eyebrow">Our leadership</p><h2>People who lead with heart.</h2></div><p>Representative roles are placeholders for this first working demo.</p></div><div className="team-grid">{team.map(([image,name,role])=><article key={name}><img src={image} alt="Leadership team member"/><h3>{name}</h3><p>{role}</p><a className="text-link" href="#contact">Read bio →</a></article>)}</div></div></section>
  <section id="how" className="how"><div className="shell"><p className="eyebrow">How we help</p><h2>Support that meets the moment—and grows with her.</h2><div className="steps"><article><b>01</b><h3>Provide a Safe Place</h3><p>Immediate and long-term housing support that centers wellbeing.</p></article><article><b>02</b><h3>Offer Holistic Care</h3><p>Emotional, educational, and practical resources for the whole person.</p></article><article><b>03</b><h3>Build Brighter Futures</h3><p>Ongoing support for independence, purpose, and success.</p></article></div></div></section>
  <section id="donate" className="shell"><div className="donate"><div><p className="eyebrow">Get involved</p><h2>Change a life today.</h2><p>Your support helps create safe housing, healing, and brighter futures for girls and young women.</p></div><div className="donate-actions"><a className="button" href="mailto:hello@rosewilllovingarms.org?subject=Donation">Donate now →</a><a className="button ghost" href="mailto:hello@rosewilllovingarms.org">Other ways to give</a></div></div></section></main>
  <footer id="contact"><div className="shell footer-top"><div><a className="brand" href="#home"><Mark/><span>Rosewill<br/>Loving Arms</span></a><p>A safe place to heal. A future to grow into.</p></div><div className="footer-links"><a href="#about">About</a><a href="#leadership">Leadership</a><a href="#">Instagram ↗</a><a href="#programs">Programs</a><a href="#contact">Contact</a><a href="#">Facebook ↗</a><a href="#impact">Impact</a><a href="#donate">Donate</a><a href="#">LinkedIn ↗</a></div></div><div className="shell footer-bottom">© 2026 Rosewill Loving Arms. First working demo.<span>Privacy Policy　|　Terms　|　Accessibility</span></div></footer>
</>; }
