"use client";

import { useState } from "react";

const A="/Rosewill/rosewill/";
const programs=[
  ["services-one.jpeg","24/7 transitional care","Residents receive therapeutic care for 6–18 months, including counseling, transportation for education, job placement, and medical attention when needed."],
  ["services-two.jpeg","Youth workshops","Bullying prevention, healthy relationships, proper hygiene, and life-skills workshops create room for practical learning and conversation."],
  ["service-card-one.jpg","School & community partnerships","Rosewill works to nurture and empower young women through essential care, skill-building, and meaningful community connection."],
];
const board=["Wileen Stokes · Founder","Jerrilyn Parson · Board of Directors","Lois Munkacsy · Board of Directors","Lisa Kilgore · Treasurer","Diane Day · Board of Directors","Roshni Muruganandam · Secretary"];
function Brand(){return <img className="brand-logo" src={A+"logo.png"} alt="Rosewill Loving Arms Covenant House"/>}

export default function HomePage(){const [open,setOpen]=useState(false);const close=()=>setOpen(false);return <>
  <header className="site-header"><div className="shell nav"><a className="brand real-brand" href="#home" onClick={close}><Brand/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Open menu" aria-expanded={open}>{open?"×":"☰"}</button><nav className={open?"links open":"links"}><a href="#about" onClick={close}>About</a><a href="#programs" onClick={close}>Programs</a><a href="#founder" onClick={close}>Our Founder</a><a href="#resources" onClick={close}>Resources</a><a href="#contact" onClick={close}>Contact</a><a className="button small" href="#give" onClick={close}>Give</a></nav></div></header>
  <main id="home">
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Rosewill Loving Arms Covenant House</p><h1>A safe place to heal.<br/><em>A future to grow into.</em></h1><p className="intro">RLACH is a safe place for girls ages 13–20 during some of the most vulnerable times in their lives—so they can overcome trauma, heal, and grow into educated, confident young women.</p><div className="actions"><a className="button" href="#give">Support Rosewill <b>→</b></a><a className="button ghost" href="#programs">Our programs</a></div></div><div className="hero-art"><img src={A+"learning.jpeg"} alt="Young person learning and creating"/></div></div></section>
    <section className="mission"><div className="shell mission-grid"><p className="eyebrow">Our mission</p><h2>To provide a safe haven with therapeutic transitional housing for those impacted by sexual abuse, sexual assault, and sex trafficking.</h2></div></section>
    <section id="about" className="story"><div className="shell story-grid"><div className="story-photo"><img src={A+"service-card-two.jpg"} alt="Rosewill program community"/></div><div><p className="eyebrow">Who we are</p><h2>A home built for recovery and possibility.</h2><p>Rosewill is designed as a transitional home for sexually abused, sexually assaulted, and sexually exploited girls. Its unique home setting gives residents a safe haven where they can focus on recovery and their future.</p><p className="eyebrow" style={{marginTop:28}}>Our vision</p><p>To assist female youth on their healing journey after sexual trauma throughout South Carolina, North Carolina, and Georgia.</p></div></div></section>
    <section id="programs" className="section shell"><div className="head"><div><p className="eyebrow">Programs & services</p><h2>Support that stays close.</h2></div><p>Rosewill brings therapeutic care, practical support, and real-world preparation together under one roof.</p></div><div className="program-grid-real">{programs.map(([image,title,copy])=><article key={title}><img src={A+image} alt="Rosewill program"/><div><p className="eyebrow">Rosewill program</p><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section id="journey" className="how"><div className="shell"><p className="eyebrow">How it works</p><h2>Thoughtful care from the very start.</h2><div className="steps"><article><b>01</b><h3>Evaluation &amp; diagnosis</h3><p>Each young lady is evaluated and assigned by a counselor or agency.</p></article><article><b>02</b><h3>Weekly care plan</h3><p>Each girl receives a custom plan based on her evaluation results, because no two traumas are exactly alike.</p></article><article><b>03</b><h3>Start of the care journey</h3><p>Physical and psychological evaluations help each client begin with the best chance for success.</p></article></div></div></section>
    <section className="impact"><div className="shell"><p className="eyebrow">What sets us apart</p><div className="stats"><div><strong>TF-CBT</strong><span>Trauma Focused Cognitive Behavioral Therapy services</span></div><div><strong>24/7</strong><span>Care availability, with same or next-day appointments</span></div><div><strong>3</strong><span>States served: SC, NC, and GA</span></div></div></div></section>
    <section id="founder" className="team"><div className="shell"><div className="head"><div><p className="eyebrow">Our founder</p><h2>Wileen J. Stokes</h2></div><p>Founder, advocate, and adult survivor of childhood sexual abuse.</p></div><div className="founder-real"><img src={A+"wileen.jpeg"} alt="Wileen J. Stokes"/><div><h3>A vision grounded in service.</h3><p>In 2009, Wileen established Rosewill Loving Arms Covenant House as a 501(c)(3) nonprofit to serve female youth who have experienced sexual trauma across South Carolina, North Carolina, and Georgia.</p><p>Her work is rooted in giving back to her community and advocating for people who have experienced sexual trauma.</p><a className="text-link" href="https://www.linkedin.com/in/wileen-stokes-1617312a2/" target="_blank">Connect with Wileen on LinkedIn →</a></div></div><div className="board"><p className="eyebrow">Board of directors</p><div>{board.map(member=><span key={member}>{member}</span>)}</div></div></div></section>
    <section id="resources" className="resources"><div className="shell"><div className="head"><div><p className="eyebrow">Resources</p><h2>Help is available now.</h2></div><p>For immediate support, please use these established crisis resources.</p></div><div className="resource-grid"><a href="tel:18006564673"><strong>Rape / sexual assault</strong><span>1-800-656-4673</span></a><a href="tel:18883737888"><strong>Human trafficking</strong><span>1-888-373-7888</span></a><a href="sms:741741?body=HOME"><strong>Crisis text line</strong><span>Text HOME to 741741</span></a></div></div></section>
    <section id="give" className="shell"><div className="donate"><div><p className="eyebrow">Give to Rosewill</p><h2>Make a safer future possible.</h2><p>Your donation supports therapeutic care, housing, education, and the everyday resources young women need to heal and thrive.</p></div><div className="donate-actions"><a className="button" target="_blank" href="https://cash.app/qr/$Rosewill2009">Give via Cash App →</a><a className="button ghost" href="mailto:wileen@rosewill.org">Contact Rosewill</a></div></div></section>
  </main>
  <footer id="contact"><div className="shell footer-top"><div><Brand/><p>Rosewill Loving Arms Covenant House</p></div><div className="footer-links"><a href="#about">About</a><a href="#programs">Programs</a><a href="#founder">Our Founder</a><a href="mailto:wileen@rosewill.org">wileen@rosewill.org</a><a href="tel:18647249876">864-724-9876</a><a href="https://www.facebook.com/profile.php?id=61582216172069" target="_blank">Facebook ↗</a></div></div><div className="shell reach"><strong>Reach us directly</strong><span>PO Box 645, Gray Court, SC 29645-0645</span></div><div className="shell footer-bottom">© 2026 Rosewill Loving Arms Covenant House.<span><a href="https://www.rosewill.org/privacy/" target="_blank">Privacy Policy</a>　|　<a href="https://www.rosewill.org/legal-notice/" target="_blank">Legal Notice</a></span></div></footer>
</>}
